# Generated by Django 5.2a1 on 2025-02-27 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('firstProjectApp', '0015_alter_ingredientamount_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuAndTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('d', 'Dinner')], default='d', max_length=11)),
                ('recipe',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='firstProjectApp.recipe')),
            ],
        ),
    ]
