# Generated by Django 5.2a1 on 2025-03-05 17:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('menu_generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='menuandtime',
            unique_together={('date', 'type')},
        ),
    ]
