# Generated by Django 5.2a1 on 2025-03-05 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('firstProjectApp', '0016_alter_recipe_name'),
        ('menu_generator', '0002_alter_menuandtime_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuandtime',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstProjectApp.recipe'),
        ),
    ]
