# Generated by Django 5.2a1 on 2025-03-14 11:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu_generator', '0004_menuandtime_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='menuandtime',
            unique_together={('date', 'type', 'user')},
        ),
    ]
