# Generated by Django 5.2a1 on 2025-04-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_generator', '0005_alter_menuandtime_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepeatingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('m', 'Monthly'), ('d', 'Daily'), ('w', 'Weekly'), ('f', 'Fortnightly')], default='w', max_length=5)),
                ('time', models.TimeField()),
                ('day', models.CharField(blank=True, choices=[('M', 'Monday'), ('T', 'Tuesday'), ('W', 'Wednesday'), ('TH', 'Thursday'), ('F', 'Friday'), ('S', 'Saturday'), ('SU', 'Sunday')], max_length=5, null=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('duration', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
