# Generated by Django 5.2a1 on 2025-04-25 10:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_generator', '0007_repeatingtask_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repeatingtask',
            name='duration',
            field=models.TimeField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
