# Generated by Django 5.2a1 on 2025-04-28 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu_generator', '0008_alter_repeatingtask_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repeatingtask',
            name='duration',
        ),
    ]
