# Generated by Django 5.2a1 on 2025-04-28 12:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_generator', '0009_remove_repeatingtask_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='repeatingtask',
            name='duration',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
