# Generated by Django 5.2a1 on 2025-04-29 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_generator', '0010_repeatingtask_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='repeatingtask',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
