# Generated by Django 5.2a1 on 2025-04-29 12:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_generator', '0011_repeatingtask_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='repeatingtask',
            name='week',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
