# Generated by Django 5.2a1 on 2025-04-29 14:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_generator', '0012_repeatingtask_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repeatingtask',
            name='week',
        ),
        migrations.AddField(
            model_name='repeatingtask',
            name='created_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
