# Generated by Django 5.2a1 on 2025-04-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_generator', '0013_remove_repeatingtask_week_repeatingtask_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repeatingtask',
            name='day',
            field=models.CharField(blank=True, choices=[('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday'), ('4', 'Friday'), ('5', 'Saturday'), ('6', 'Sunday')], max_length=5, null=True),
        ),
    ]
