# Generated by Django 5.2a1 on 2025-05-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_generator', '0015_alter_repeatingtask_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repeatingtask',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
