# Generated by Django 5.2a1 on 2025-02-07 20:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('firstProjectApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
