# Generated by Django 5.2a1 on 2025-02-08 11:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('firstProjectApp', '0003_alter_recipe_duration_alter_recipe_ingredients_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='duration',
        ),
    ]
