# Generated by Django 5.2a1 on 2025-02-08 11:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('firstProjectApp', '0004_remove_recipe_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
