# Generated by Django 5.2a1 on 2025-02-12 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('firstProjectApp', '0005_recipe_duration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('public', models.BooleanField(default=False)),
                ('units', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstProjectApp.unit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(blank=True, to='firstProjectApp.ingredientamount'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='ingredientTag',
            field=models.ManyToManyField(to='firstProjectApp.ingredientamount'),
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
