# Generated by Django 5.2a1 on 2025-02-17 12:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('firstProjectApp', '0007_ingredient_ingredientamount_ingredient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipestep',
            name='duration',
        ),
        migrations.AddField(
            model_name='recipestep',
            name='shortDesc',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='recipestep',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
