# Generated by Django 5.2a1 on 2025-02-18 17:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('firstProjectApp', '0010_alter_recipestep_options_alter_recipe_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipestep',
            name='order',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
