# Generated by Django 5.2a1 on 2025-02-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('firstProjectApp', '0012_ingredientamount_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='calories',
            field=models.IntegerField(blank=True, null=True, verbose_name='Calories per 100g'),
        ),
    ]
