# Generated by Django 5.2a1 on 2025-02-24 10:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('firstProjectApp', '0013_alter_ingredient_calories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ingredient',
            unique_together={('name', 'user')},
        ),
    ]
