# Generated by Django 5.2a1 on 2025-03-03 11:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('firstProjectApp', '0015_alter_ingredientamount_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=250, null=True, unique=True),
        ),
    ]
