# Generated by Django 5.2a1 on 2025-03-11 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstProjectApp', '0016_alter_recipe_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='serves',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='recipe',
            name='source',
            field=models.URLField(blank=True, null=True),
        ),
    ]
