# Generated by Django 5.2a1 on 2025-03-12 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstProjectApp', '0017_recipe_serves_recipe_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='conversionToGrams',
            field=models.FloatField(null=True),
        ),
    ]
