# Generated by Django 5.2a1 on 2025-03-12 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstProjectApp', '0018_alter_unit_conversiontograms'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ingredientamount',
            unique_together={('ingredient', 'amount', 'units', 'details')},
        ),
    ]
