# Generated by Django 5.2a1 on 2025-04-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstProjectApp', '0020_pushnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushnotification',
            name='current_active',
            field=models.BooleanField(default=False),
        ),
    ]
